---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocp-virt-migration-agent-secret
  namespace: ocp-virt-agent
spec:
  encryptedData:
    openai-api-key: AgBlHeg6xnh0aUkWuk9EeHHXRF6+n910EfPXu1GZytWKLvtfPivU0hq92K0dRtB4MCfR4bSQEGnVzljGKlV6zuclOGeZRc2cniZ6AmLu/U4j45TjkI30LWAJVE0GE/6l+Tm4uzAMwDMMV24Gq5hlqbtNpcQ6kjzaWHKt8lW5vdSUqh+e/wR9UTjmQFvDWD5gxUrI1l+3iWwkFDuqPS4U47BWd5CbiWcYOewtFY3JrJ7nFyojqXoJrJf1w2t4IMqEwEF61DKgudByYJ0SMedtfej9DGTyFqR3cLFs0Oa3PEbM1f5YF+g1QcgLpRrAieUviLb6N0ozvAOeSV6w1locDKvat0BToF873rOwO+6yu012PxWnpfUXhPCHZRuO/IZBBhUySm90wyEHYFjo0jKlW6M4ubtemENfo2XLBbKYfTKGhIS5uQx3MKsaZ4/n3r20NTjWl3xLUc+f3bzUe4tJc0aCj24boxvrr4cgwEaUGHMW8PjXfxtkUgMqQ4ajwM/Mm+6ksaCwo7tIbiBoMFm//0li7mBrVYYUoDUs9u29d+ZPs20vAPLzdKEJmFP+RDS/wxuy9OalBjeWsjiJ26rJxkthObbFqvQZfnDIduHQlWUAe47esigR0z4EHIOtHpjJXpYGRF2b9/sDv2qzQ6WYylxC7r09a7hCku5abzUVZC3l+uYfBLyP7Xu0AHlvWYUVGRiRQX6Aff1bMKaHM5a6LPSJNJnUr0T4udcSRVDuxH6vH+KHRZ0QXcWNOQOFGvVTqcUUoFvBWg==
  template:
    metadata:
      name: ocp-virt-migration-agent-secret
      namespace: ocp-virt-agent
    type: Opaque
