---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocp-virt-migration-agent-secret
  namespace: ocp-virt-agent
spec:
  encryptedData:
    gemini-api-key: AgAaJi8fst6AkYN42kAles2V3gZNpTMAD7OJxYbpo+KxR+2LRdmG31NiY96iLGHNlA16e10iB38Yh7q34Wj10jMGVMcxUdJXBtvN/C6Pz5xrYRT+8GphrD3P97PTeq6Mcqn2h4tbwvizw9/jb+5Mxm+t9GG4ktlR5Imm2XnTbe0VM7/FjDXdSN0DLyLshxTx2rTInXsweg1Vvdn2jCV9dP8aCSz2PSrj/fi8ED/3GHYyxd13liu3EsYoiU/iJHkISySUudXXq+eUbhPqCX/hSnGnJ7qziDDqxQL6jXNNntoeVvmstWd/HhFJaLdQ90AqCgDaK5H4CNAEyyk8CgfvOOgeQvG3j72cs54OOK3vfR61TWRuJOJ9suBRpJonJk/Rb2ZVCIT5zoQn65g3skYa5n/PZsdMonDoS6cvWf0PiDl6+qj2gAbvlzKQAgQxiydF7Cddy/7z3WbZ6G68pnYLu/iboLUyY+xaK1x2cgk1QuTa8QVJ6ZG4zveiS60eH3HZwSRdTGpz5CSconM8kNM1YY1/Wive+2ID9q1nA3IGdt+c+CTM4IPKsCmTzTRaDR13W4uCGGzR0gdPn7ZgiSaDAfOrqaXqOCSN0BHqUopEXTm5CPel+ld3mWxvDXlWOOgrWQIO9b3a65SdKH9Dss8EDzyPux6uCYeISvzmAZJlE7wMTc7BjAYrDo7jXX9tFQSfprsK4EgdXnwsI+CfPBLWIprwvBrvevWMwoGrYDsz5o2T4SBZTTG4+InNXsZjwLS7qsUp8RwO7WFNO0e0n8UpFeYIUH1kIw==
    openai-api-key: AgCh9dT7j1WFXXIcVFhWgo0f7exnr0wIkrHInXQOTOWqU0NjpGIAUyVKr1tt+Fq2ZsmbUv04kBKfm3Pnacpn4ScUTJBEOAN5F/Scxo3oF4P/easf4q9j8PWP2yPa+K2NaTKBpiIeHj5B5SbqUa2KDTuOK4BKggBh7BrhCgfCzZ2BrHkPfIOSwxvzb4PVWhyAdERj+knayttOVVM6RLv4Z4am3Kim0opt3e6rK6Omw87JRFpzOZcTUNSKpOWcJ6CjFW8NTekav/OS7ZMaVmbxxYO39SrnFZB1XoexWjBAcNp6qFuHpiqlOgFF49YuCGfUTY9L2HGNwBGEiYfeYKgtebFF9D6l5l3D5ZeJGKOayb8Y/qhhb3JtbMD7IR6B0SMwiXN1zwTnxWRdBM8xVr7HAXq/1FhyZyfPsr33hwkvHz9DLp95lxq5CCroub68DlUsnkY4zc58SbyoLwAlufOgLLR0R7lb6NlK5XkeQpWFiE+Ry/ZBlL0ngO2sDzvEE9ro+NScUvsrnKcI4aiGXot/NgLMELZYeUlmvWCkB0nXoG6FE1mSUVWnmDEelnQIDjMQafNYixlX24VZfPp7cDCpdBF89dhpjkys3PaXD6oO/bIYhzQC49kVc+qFdpNgX2VN2U+vUCYZv/A99F+9c6ZNML8BX7WU8ITcICSOWXwZEsTV/wx27ZmULDcTQhjMM2ThQMYps2cbVfEYUJ2IOKPLAM8AvTmGNMHNiXNQF3PBsXypltTaBm0LV5A6CsgXk9DFY6Z3mhktOH3cEbf7CrCKrRwT1wIc/g==
  template:
    metadata:
      name: ocp-virt-migration-agent-secret
      namespace: ocp-virt-agent
    type: Opaque
