---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocp-virt-migration-agent-secret
  namespace: ocp-virt-agent
spec:
  encryptedData:
    gemini-api-key: AgBqmEUVectYXcE699Blh2ad1c20AcMuueuY4ENGodTz+sc+9NFZf6E+Wq8HTpIjDsLZo70Zav0lEiFh+dNpsReUZdgUhXKmz1TgdOi1hnDhy6gr05KcueIwot7kbgqChZvc2TWw1f/t9BDab1h4pQ60uzsAIV2PwS91r+yJ+Bq1ngyxI9rV8PfUSqOCMsmMLv/RzBGhzrjy0nOo/HysbAebwMwgpbPFneLpPqoni818X9W5sz0FIB0tG0ytF8pcBauy4cmho/mU1UJC5j8Y565h1GUoDW5ZufcomRrp5fFnOvWEeI/4UykWB4WCq4n8k6FM0DR5pWzXJowcR4UbBJek1tLxCxamZaziUBYfbXh72vXsDdh1aOzUQWP6ZQgLzKQ9I5UHvUUASjgag1VjnF6SpmIR9q0aTaM/sKNosxv+b8dK7zostjwPovWo1fQxdG5g+UzRlTQkz+Ejp7sdPmcmSQzDXpnOxPZgNrxnreMkh/WIJRJJL98/guMQkGP3H6+HDNUPWCkDgDrPs/TyZWyOs75XP9PoBrtbdYFz6RxJ5111d4PLS+faIhO9RJTj0OylTxjVPiEXinEgf9DOgmM5Nl/9gG+k4CQ2KBkmdKHbOBFgl18EfIsTfZ2ZF7DjNazQwFvAGB9AkLV0MQZR7OB5b1XpJmvYhPSiSg0ANeDfd5GpKv/ax0pWe1yjjHRQU/mcNsRsHexl9fILCyDk2n94Vb+DoZ2FiMLqREJNHmtQyRYII4hcvSS2dw5cIhoEBVqZy1Tox2GWJpJfA0YTqn0W24M9mg==
    openai-api-key: AgAP37/glUV7J/lTJ/z8o2vHzDU3iUtQ3eZoC/6R/Et39emRBlEx9kUuEXKIqMwrarqRJxdQWGiiXg344Yj7imw/XYVrlJ1JAewncoVErmXWToQDViMTXURN5DAokXDHPCi0cvk1fTqZ1hE2Kdljcc20fecr9BgK0Qg0VWcHUR0+z7MgZ8qg2jWn4xRX1eCJaAtpoVLvZf4UXtzTORe4MQDVXlDvVHTq8iVB6vMfocVzD6rZM5PhCBhbtdCDtz+jVzbhla90huu20qo7hTU7HlkE5GhmTtXRlC1DPCj0wRX90hBLkqXmLje1PWLX+ep71s9YXcWPF4WYwtBQvdgsURJQzixfmJF9/tj+0BRp4n+HGyiNTJLsSlTF7M5WQAGaGN1X7wjap9r/FVIXlHHcn3saZKR4SR4gFziZDJoscLDW8wor/DWvKb0uGqIf5v5b5l/sJWpFqeZMNauFNNXUMWyBv6xjaJCJKVA1IwqzfXtTvVXGrl9DLZtJcUOIfmdc5X3M444ExMAauSD3Nd9AR8iKJbekiIzVBtesyezaErkWw9eGsxJaraeJiEqW93JMy993CQccvBZSX8/0BPwBorveT01OPDEdtynelb9e5fABsK1eJmPHERvSw4r5ql/S9PN+3yfGl90cUKAH9ZptCLi0JgktVeJX1niSlfldGBQTJTfKxnukHJ93Gjwf47gapZHgvoq4VTNNN0P0cUGkqhnXoSjHnKQI2AYbIfm6BpPUsBJu6NysETn0baeLtjm182XpMByh7T3QbB7zLLq8asKsGU+AHg==
  template:
    metadata:
      name: ocp-virt-migration-agent-secret
      namespace: ocp-virt-agent
    type: Opaque
