---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocp-virt-migration-agent-auth
  namespace: ocp-virt-agent
spec:
  encryptedData:
    gemini-api-key: AgAWiCALlM8o+6izFJFVF4GoGGXeNbgJRY+Mp2HPdF5kalTEnoTM2OFqv3qRgOkMMMBDBJdY/TH25KbnwMRtIo7kSdpXDAUNSaCdVwmhh0Glu67QHUcg4C/7tCt0SzDPTezGlntffsDBCkVm9juJUF6Kj68ppLAvQLgOrI4FYYEbjDNsmY7AqP0UmeXJycSm3FPNaSOFv2Fbce1ENbtw+9X5Vb7v01YRUgsAkTwmiGkPMa6tejHJEJKB3/KRQOTSfk5TFYaj3OBGhuT3sAAk0bQReuFM7I3m/9OC2cLxS5sxcOFI1CF3oBMnfXY/A7PSdg0sQFu8DHftvXd3z9e6Fy/my3p4JtqvH7oIhDe7IUKC04IBEfCqXo0ykGiGdLy1P52lbHpW8aS4pbNn04WzSpqHsOJmD+BxKZgvKYG/ts14mWbdDGGGLutJXunf8JhJUh3klYfU+ujDXbhDhjw8kWrRQ8bIwSN5STz2RNF3g7Y6CGKLhw6+fFIg8rcO9TO46ojs72urA8ZX5F4fHHSXIWdPe92AdawICTZHw5OBq9fNTDi6ZJ2z+s5r3XnJkhNbirJxdoaX/HYS/l9t07DCsLbXKXUwq3FQ0lEa+fXWJHhSWl6LWn60zwzu0uBKPbTrYqIKPZgJA9Xx62VW2PTeC0BUAltj0WkbeZ62xHEAF8UJ3Dtpv0sZqxK1x8rVhx6t9PFDN7kNjk7Qpktn6uApxl3Az+d0N5FAZpl+u8ujmVvXFiY/vY5z/dnelLixZlEIT04tps8OXA==
    mtv-api-token: AgA/MrYVCrZRHNlRR7yGLoj/atAfvgoNunA6Asxlx52AmOcDOCqknZCKdzIY1Ee0U8Ok5e6hyfEs9LPa5HzCjSyAcUMUbgD7TFSjiA9ee0amMz8zUEUcGB9TUnNodtaotQ7rGdeodSkBt/aRHbQ8k+iO1DyebBjTLjZX1DlQJdql+9mISPeHO1JzZHnpmkp3fSRpJfbH2HStoLYgqGu7BVK0dxtG4xtrPr0xr9x+mLssOJI6UaMwjz9/yVGH3TAtChkYBWypdk4EvA3DNwk/bYkKTv2KOGAKKuFD6+zYZ33GEH3CkO8YDYYSHzS9YGjgUnRd1IVPe25UlNASxRAD1fh9qRT7ZqDugoyaeUAvxJJQh8bS4N1LEw795Bvp2rQ9cTib1Gd7rLDu3Ikdg7LW8T9uxqs6aolnG7LdmJ7SvuEU/f7VMWoKYO4I/cNfnr7iOPshcugQujMuTbhs5/5smVE1ptLueoGdjOJY6felW5QGchtSEmS1d1T1IWjmcbdGL590FXEySxBSAa6m+Vscp0xx346+LqIXHXHh2ADFz+XCHotP7g4KtAjZ+i0YnqBKgGpUqZsRdU6cRK0Z9CeT0n2cdj3uQ5C+JxGspU/nbryvkyKz6CWOw6EfHapzzPZulumJ3Wgm9hgYKZ6YJnB2F06yAG+luJRGPpYBoNejedcNxD/PPYOeH+NqJF+HzQmJGSw=
  template:
    metadata:
      name: ocp-virt-migration-agent-auth
      namespace: ocp-virt-agent
    type: Opaque
