apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocp-virt-migration-agent-openai
  labels:
    app: ocp-virt-migration-agent
    app.kubernetes.io/part-of: ocp-virt-migration-agent
  annotations:
    haproxy.router.openshift.io/timeout: 600s
    haproxy.router.openshift.io/timeout-tunnel: 600s
spec:
  to:
    kind: Service
    name: ocp-virt-migration-agent
  port:
    targetPort: openai
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
